#Chapter 3 example 5
#find 7*p, where p is (15,86) in field 223, on curve a = 0, b = 7
from ecc import FieldElement, Point
prime = 223
a = FieldElement(0,prime)
b = FieldElement(7,prime)
x = FieldElement(15,prime)
y = FieldElement(86,prime)
p = Point(x,y,a,b)
print("7*p = " + str(7*p))

#Chapter 3 exercise 5
#for the curve y^2 = x^3 + 7, over F_223, find the order of the group generated by (15,86)
inf = Point(None,None,a,b)
product = p
count = 1
while not (product == inf):
	product += p
	count += 1
print("order = " + str(count))
